var a;
a = "hello";
a = 10;
console.log(a);
console.log("welcome to ts");
var value;
value = true;
value = 89;
value = "hello";
value = [];
value = {};
value = undefined;
console.log(value);
var value1;
value1 = true;
value1 = 56;
value1 = "Bye";
value1 = [];
value1 = {};
value1 = undefined;
console.log(value1);
